// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    CiGithub: typeof import('~icons/ci/github')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IcRoundMenuBook: typeof import('~icons/ic/round-menu-book')['default']
    LogosGithubIcon: typeof import('~icons/logos/github-icon')['default']
    Music: typeof import('./components/Music.tsx')['default']
    NotoHeartSuit: typeof import('~icons/noto/heart-suit')['default']
    OneSay: typeof import('./components/OneSay.tsx')['default']
    README: typeof import('./components/README.md')['default']
    RiArrowDownSLine: typeof import('~icons/ri/arrow-down-s-line')['default']
    SimpleIconsGitee: typeof import('~icons/simple-icons/gitee')['default']
  }
}

export { }
