// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BiArrowUpCircle: typeof import('~icons/bi/arrow-up-circle')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CiGithub: typeof import('~icons/ci/github')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DocList: typeof import('./components/DocList.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IcRoundMenuBook: typeof import('~icons/ic/round-menu-book')['default']
    MdiLightEmail: typeof import('~icons/mdi-light/email')['default']
    Music: typeof import('./components/Music.tsx')['default']
    MyCard: typeof import('./components/MyCard.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NImage: typeof import('naive-ui')['NImage']
    NotoHeartSuit: typeof import('~icons/noto/heart-suit')['default']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NTable: typeof import('naive-ui')['NTable']
    NTime: typeof import('naive-ui')['NTime']
    NTimeline: typeof import('naive-ui')['NTimeline']
    NTimelineItem: typeof import('naive-ui')['NTimelineItem']
    OneSay: typeof import('./components/OneSay.tsx')['default']
    README: typeof import('./components/README.md')['default']
    RiArrowDownSLine: typeof import('~icons/ri/arrow-down-s-line')['default']
    SimpleIconsGitee: typeof import('~icons/simple-icons/gitee')['default']
    Step: typeof import('./components/Step.vue')['default']
  }
}

export { }
